# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tcosta-d < tcosta-d@student.42porto.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/29 16:16:51 by tcosta-d          #+#    #+#              #
#    Updated: 2023/05/29 16:17:32 by tcosta-d         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:

bonus:

clean:

fclean:

re:

teste:

.PHONY: all bonus clean fclean re teste